【202_204】スワイプシステム完成形
enpitut2022/a-meshireco pull request #6
Opened 2022-07-26 15:18 UTC by 9re-pe

2022-07-26 23:16 UTC, monokemonoke requested changes
PRありがとうございます✨
Netlifyのプレビューがコケてるので, 
見れるように修正していただけると嬉しいです〜！！
よろしくお願いいたします！！

2022-07-26 23:16 UTC, monokemonoke commented on src/App.tsx
> +    <div className = 'App'>
`COMMENT`
もしかしたら, className と イコールの間のスペースが原因でうまくbuildできてないかもしれないです！
もし違ったら無視してください〜

2022-07-26 23:16 UTC, monokemonoke commented on src/components/cards.tsx
> +// ...
`FIXME`
7行目のコメントアウトはいらないはずなので消していただけるとありがたいです〜！！

2022-07-26 23:16 UTC, monokemonoke commented on src/components/cards.tsx
> +import React, { useRef, useMemo } from 'react'
`FIXME`
自分が追加したので申し訳ないのですが、
 `useRef` が使われていないので削除していただけると嬉しいです〜！！

2022-07-26 23:16 UTC, monokemonoke commented on src/components/header.tsx
> +// @ts-ignore
`COMMENT`
header を分ける提案ありがとうございます！！
あくまで1意見なのですが, このPRでは「スワイプシステムの完成」だけに絞って、
headerに分けるのは別のPRにするのがいいかなと思いました〜！！

2022-07-26 23:16 UTC, monokemonoke commented on src/components/header.tsx
> +const header = (props: StoreProps) => {
`FIXME`
headerコンポーネントは使うときに引数をとらない (propsを埋め込まない) と思うので, 
`props: StoreProps` という部分を削除していただけるといいかと思いました！！

2022-07-26 23:16 UTC, monokemonoke commented on src/index.css
> +.tinderCard {
`FIXME`
もしかしたらGithubの問題かもしれないのですが、
インデントが乱れているので直していただけるとありがたいです〜！！

2022-07-27 00:38 UTC, 9re-pe commented on src/components/cards.tsx
> +// ...
@monokemonoke 消しました

2022-07-27 00:40 UTC, some0419 approved these changes
OKです

2022-07-27 00:41 UTC, 9re-pe commented on src/components/header.tsx
> +// @ts-ignore
@monokemonoke 

それはちょっと思った

めっちゃ正直このPRめっちゃリファクタリングしてて分けると膨大になるので今回だけ見逃してほしいです、、

2022-07-27 00:42 UTC, 9re-pe commented on src/components/header.tsx
> +const header = (props: StoreProps) => {
@monokemonoke 
ほんとだ！消しました！

2022-07-27 00:47 UTC, 9re-pe commented on src/App.tsx
> +    <div className = 'App'>
@monokemonoke 一応動いてる、、、

2022-07-27 01:05 UTC, monokemonoke approved these changes
@9re-pe 
プレビューみたけどめっちゃいい感じやね！
ありがとう〜〜！！

2022-07-27 01:05 UTC, monokemonoke commented on src/App.tsx
> +    <div className = 'App'>
あ、netlifyのプレビューも動いたみたいだね！！
ごめんこっちのかんちがいかも！

2022-07-27 01:05 UTC, monokemonoke commented on src/components/header.tsx
> +// @ts-ignore
たしかに、今からわけると無駄な時間が増えるかもだから今回は通したほうがいいね！
次回からは分けたい！笑

2022-07-27 01:07 UTC, merged